os: linux

language: generic

dist: bionic

services:
  - docker

before_install:
  - docker build -t yeongbba/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true yeongbba/react-test-app npm run test

after_success:
  - docker build -t yeongbba/docker-frontend ./frontend
  - docker build -t yeongbba/docker-backend ./backend
  - docker build -t yeongbba/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push yeongbba/docker-frontend
  - docker push yeongbba/docker-backend
  - docker push yeongbba/docker-nginx

  deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "docker-fullstack-app"
    env: "DockerFullstackApp-env"
    bucket_name: "elasticbeanstalk-ap-northeast-2-924744414500"
    bucket_path: "docker-fullstack-app"
    on:
      branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
